### ISSUE TITLE
license question

### ISSUE THREAD

**Issue by IzzySoft** [Chandigarh-University-students/Music-Player#3]
May I ask what license your code is using? Thanks!

**Comment by rishabhkumar812** [comment]
> May I ask what license your code is using? Thanks!

License is updated. 
It is GNU General Public License v3.0.

**Comment by IzzySoft** [comment]
Thanks! Updated on my end. I've made your app [available here](https://apt.izzysoft.de/fdroid/index/apk/com.projects.musicplayer) so people can find it easier and keep it automatically updated; be welcome to link to that address and, if you wish to, use the [corresponding badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) :smiley:

(Updates are fetched automatically within 24h of your attaching the APK to a new release)

**Comment by amanr11314** [comment]
@IzzySoft Thanks for helping out to publish our app to open source. However, on the download link it is still showing Licence as Unknown. Please update that or help us do that.

**Comment by IzzySoft** [comment]
@amanr11314 as pointed out, sync happens every 24h. I've already applied the correction, it will show up in about 3h from now when the next sync runs. Apologies if I was not clear about that.

**Comment by IzzySoft** [comment]
Please also remember adjusting `versionName` and especially increasing `versionCode` with each release. The APK at tag v1.1.0 identifies as 

    package: name='com.projects.musicplayer' versionCode='1' versionName='1.0'

while it should be

    package: name='com.projects.musicplayer' versionCode='2' versionName='1.1.0'

`versionCode` is what Android uses to tell versions apart – so no user who had v1.0 installed will receive any update notification, as to Android it seems to be the very same version.
